name: "Dhondhu Maharaj"

on: 
  push:
    branches:
      - 'features/**'
      - 'main'
      - 'hotfix/**'
jobs:
  terraformInit:
    name: dhondhu-maharaj
    runs-on: devops-boss
    steps:
    - name: dhondhu maharaj rocks!
      run: echo sarvesh-devops
      
    - name: tondu maharaj rocks!
      run: echo sar-devops

    - name: rondu maharaj rocks!
      run: echo skp-devops

    
