name: "Lucky-Kabootar"

on: workflow_dispatch

jobs:
  terrafor-job:
    name: infra ki pipeline
    runs-on: devops-boss
    steps:

      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.13.1

      - name: Terraform init/plan
        uses: comu2e/tfnotify-composite-action@1.0.4
        with:
          name: terraform init
          
          
           


        
 

    
